import fs from 'node:fs';
import {chromium} from 'playwright';
const out='art/reviews/ironspine-range/rotation-1';
const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:412,height:915}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
const save=JSON.parse(fs.readFileSync('.dream-loop/heartwood-circuit/original-save-private.json'));
await page.addInitScript(s=>localStorage.setItem('wildkin.frontierProgress',JSON.stringify(s.progress)),save);
await page.goto('http://localhost:8080/');await page.waitForFunction(()=>window.__game?.frontierChunks);await page.locator('[data-action=start]').click();
async function place(x,z){await page.evaluate(({x,z})=>{const g=window.__game;g.frontierChunks.update({x,z},{activeSectionId:'camp'});g.characterPhysics.setPosition({x,y:g.frontierChunks.getHeight(x,z)+.7,z});g.playerController.syncPosFromPhysics();g.playerController.snapRenderPose();g.cameraFollow.orbitBy(-g.cameraFollow.getYaw());g.cameraFollow.snap();},{x,z});await page.waitForTimeout(3500);}
async function snap(){return page.evaluate(()=>{const g=window.__game,T=g.THREE;const rocks=[0,1].map(i=>{const object=g.scene.getObjectByName('ironspine_rock_'+i);if(!object)return null;object.updateWorldMatrix(true,true);const b=new T.Box3().setFromObject(object),c=b.getCenter(new T.Vector3()),id='-42,-64:ironspine:rock:'+i;const hit=g.characterPhysics.castRay({x:c.x,y:b.max.y+2,z:c.z},{x:0,y:-1,z:0},20,{acceptCollider:v=>g.physicsWorld.getColliderSurfaceId(v)===id});return {id,bounds:{min:b.min.toArray(),max:b.max.toArray()},hit:hit?{id:g.physicsWorld.getColliderSurfaceId(hit.collider),point:hit.point,normal:hit.normal}:null};});return{pos:{...g.playerController.getState().pos},health:g.playerCombat.getHealth(),rocks,surfaceIds:g.physicsWorld.staticColliders.map(c=>g.physicsWorld.getColliderSurfaceId(c)).filter(id=>id?.includes(':ironspine:rock:'))};});}
const contacts=[];
for(const [i,x,z] of [[0,-2080.4,-3159],[1,-2081,-3156.2]]){await place(x,z);const before=await snap();await page.keyboard.down('d');await page.waitForTimeout(3000);await page.keyboard.up('d');const after=await snap();await page.screenshot({path:out+'/r1-rock-contact-'+i+'.png'});contacts.push({i,before,after,stoppedBeforeRockCenter:after.pos.x<(after.rocks[i].bounds.min[0]+after.rocks[i].bounds.max[0])/2,actualDisplacement:after.pos.x-before.pos.x,freeExpectedDisplacement:2.145*3});}
const before=await snap();await place(400,400);const away=await snap();await place(-2080,-3160);const returned=await snap();
const report={note:'Shipping meshes and actual Rapier surfaces. Separate diagnostic supported starts, ordinary D contact; diagnostic streaming away/back. Not travel proof.',contacts,before,away,returned,checks:{initialTwo:before.surfaceIds.length===2,awayZero:away.surfaceIds.length===0&&away.rocks.every(x=>x===null),returnedTwo:returned.surfaceIds.length===2&&returned.rocks.every(x=>x?.hit?.id===x.id),contacts:contacts.every(x=>x.stoppedBeforeRockCenter&&x.actualDisplacement<x.freeExpectedDisplacement*.8&&x.before.health===x.after.health)},errors};
fs.writeFileSync(out+'/r1-native-contact.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({checks:report.checks,contacts:contacts.map(x=>({i:x.i,displacement:x.actualDisplacement,pos:x.after.pos})),errors}));
