import fs from'node:fs';import{WORLD_DATA}from'../../src/world/data/world.generated.js';import{sampleFrontier}from'../../src/world/frontierTerrain.js';import{sampleFrontierForageChunk}from'../../src/world/frontierEcology.js';import{sampleFrontierWildlifeChunk}from'../../src/world/frontierWildlife.js';import{sampleFrontierSceneryChunk}from'../../src/world/frontierScenery.js';
const asset=WORLD_DATA.visualAssets.find(a=>a.id==='asset_verdant_cliff_buttress'),opt={visualAssets:WORLD_DATA.visualAssets},route=JSON.parse(fs.readFileSync('art/reviews/ironspine-range/rotation-1/lattice-path-corridor-audit-r2.json')).route.orderedLatticePath;
const cross=(a,b,c)=>(b.x-a.x)*(c.z-a.z)-(b.z-a.z)*(c.x-a.x);
function hull(points){const sorted=[...new Map(points.map(p=>[p.x+','+p.z,p])).values()].sort((a,b)=>a.x-b.x||a.z-b.z),a=[],b=[];for(const p of sorted){while(a.length>1&&cross(a.at(-2),a.at(-1),p)<=0)a.pop();a.push(p);}for(const p of sorted.toReversed()){while(b.length>1&&cross(b.at(-2),b.at(-1),p)<=0)b.pop();b.push(p);}return[...a.slice(0,-1),...b.slice(0,-1)];}
const sd=(p,a,b)=>{const dx=b.x-a.x,dz=b.z-a.z,t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.z-a.z)*dz)/(dx*dx+dz*dz||1)));return Math.hypot(p.x-a.x-dx*t,p.z-a.z-dz*t);};
const inside=(p,h)=>h.every((a,i)=>cross(a,h[(i+1)%h.length],p)>=-1e-8),pd=(p,h)=>inside(p,h)?0:Math.min(...h.map((a,i)=>sd(p,a,h[(i+1)%h.length])));
const intersect=(a,b,c,d)=>cross(a,b,c)*cross(a,b,d)<=0&&cross(c,d,a)*cross(c,d,b)<=0&&Math.max(Math.min(a.x,b.x),Math.min(c.x,d.x))<=Math.min(Math.max(a.x,b.x),Math.max(c.x,d.x))+1e-8&&Math.max(Math.min(a.z,b.z),Math.min(c.z,d.z))<=Math.min(Math.max(a.z,b.z),Math.max(c.z,d.z))+1e-8;
const segmentPoly=(a,b,h)=>inside(a,h)||inside(b,h)?0:Math.min(...h.map((c,i)=>{const d=h[(i+1)%h.length];return intersect(a,b,c,d)?0:Math.min(sd(a,c,d),sd(b,c,d),sd(c,a,b),sd(d,a,b));}));
const sources=[],homes=[],solids=[];for(let cx=-43;cx<=-41;cx++)for(let cz=-65;cz<=-63;cz++){sources.push(...sampleFrontierForageChunk(cx,cz,opt));homes.push(...sampleFrontierWildlifeChunk(cx,cz,opt));solids.push(...sampleFrontierSceneryChunk(cx,cz,opt).filter(i=>i.kind==='canopy'||i.assetId==='asset_fen_stone'));}
const records=[];for(const s of[{x:-2078,z:-3159,yaw:Math.PI/2,scale:.65},{x:-2077,z:-3156,yaw:0,scale:.65}]){const points=[];for(let i=0;i<asset.collision.vertices.length;i+=3){const x=asset.collision.vertices[i]*s.scale,z=asset.collision.vertices[i+2]*s.scale;points.push({x:s.x+x*Math.cos(s.yaw)+z*Math.sin(s.yaw),z:s.z-x*Math.sin(s.yaw)+z*Math.cos(s.yaw)});}const poly=hull(points),samples=[...poly,{x:s.x,z:s.z}];for(const[a,i]of poly.map((a,i)=>[a,i])){const b=poly[(i+1)%poly.length],n=Math.ceil(Math.hypot(b.x-a.x,b.z-a.z)/.1);for(let j=1;j<n;j++)samples.push({x:a.x+(b.x-a.x)*j/n,z:a.z+(b.z-a.z)*j/n});}for(let x=Math.min(...poly.map(p=>p.x));x<=Math.max(...poly.map(p=>p.x));x+=.1)for(let z=Math.min(...poly.map(p=>p.z));z<=Math.max(...poly.map(p=>p.z));z+=.1)if(inside({x,z},poly))samples.push({x,z});for(const p of samples)p.y=sampleFrontier(p.x,p.z).height;samples.sort((a,b)=>a.y-b.y);const min=samples[0],max=samples.at(-1),routeMargin=Math.min(...route.slice(1).map((b,i)=>segmentPoly(route[i],b,poly)));
const source=sources.map(i=>({id:i.id,clearance:pd(i.pos,poly)-(i.visualAsset?.id==='asset_iron_ore_rock'?.93:i.type==='tree'?1.35:i.type==='fiber'?.55:.9)-1.2})),home=homes.map(i=>({id:i.originId,clearance:pd(i.homePos,poly)-Math.max(i.roamRadius??0,i.leashRadius??0)-1.2})),solid=solids.map(i=>({id:i.id,clearance:pd(i,poly)-(i.kind==='canopy'?1.45:1.14)*(i.scale??1)}));
records.push({...s,baseX:min.x,baseZ:min.z,baseY:min.y,footprint:poly,support:{samples:samples.length,min,max,span:max.y-min.y},routeMargin,minSource:Math.min(...source.map(p=>p.clearance)),minHome:Math.min(...home.map(p=>p.clearance)),minSolid:Math.min(...solid.map(p=>p.clearance)),conflicts:{source:source.filter(p=>p.clearance<0),home:home.filter(p=>p.clearance<0),solid:solid.filter(p=>p.clearance<0)},pass:max.y-min.y<=.32&&routeMargin>=1.2&&[...source,...home,...solid].every(p=>p.clearance>=0)});}
fs.writeFileSync('art/reviews/ironspine-range/rotation-1/fallback-exact-footprints.json',JSON.stringify({note:'Exact convex XZ hull from all collision vertices, inside-aware point/polygon distance and full route segment/edge intersections; dense0.1m footprint/edge terrain support. Corrects earlier use of arbitrary collision-vertex order as polygon. Only the existing two approved placements evaluated, no new search.',records,pass:records.every(r=>r.pass)},null,2));console.log(JSON.stringify(records.map(({footprint,...r})=>r)));if(records.some(r=>!r.pass))process.exitCode=1;
