import {chromium} from 'playwright';import fs from 'node:fs/promises';
const out='.dream-loop/overnight2-survey/review';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:844,height:390},hasTouch:true,isMobile:true,deviceScaleFactor:1});
const r={reviewer:'camp_native_review',fixture:'Independent fresh isolated save. Ordinary Camp Travel/map, keyboard walking, mouse orbit, native chest and auto-harvest UI. Read-only position-guided navigation; no teleport, grants, camera overrides or save seed.',errors:[],steps:[],captures:[]};
page.on('pageerror',e=>r.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')r.errors.push(m.text());});
const position=()=>page.evaluate(()=>({...__game.playerController.getState().pos,yaw:__game.cameraFollow.getYaw()}));
async function walk(x,z,tolerance=.35){let held=new Set(),last=await position(),stuck=0;try{for(let i=0;i<130;i++){const p=await position(),dx=x-p.x,dz=z-p.z;if(Math.hypot(dx,dz)<tolerance){r.steps.push({walkTo:[x,z],arrived:p});return p;}const right=dx*Math.cos(p.yaw)-dz*Math.sin(p.yaw),back=dx*Math.sin(p.yaw)+dz*Math.cos(p.yaw),next=new Set();if(Math.abs(right)>.22)next.add(right>0?'d':'a');if(Math.abs(back)>.22)next.add(back>0?'s':'w');for(const k of held)if(!next.has(k))await page.keyboard.up(k);for(const k of next)if(!held.has(k))await page.keyboard.down(k);held=next;await page.waitForTimeout(160);const q=await position();stuck=Math.hypot(q.x-last.x,q.z-last.z)<.015?stuck+1:0;last=q;if(stuck>12)throw Error(`Walking blocked toward ${x},${z} at ${q.x},${q.z}`);}throw Error(`Walk time bound ${x},${z}`);}finally{for(const k of held)await page.keyboard.up(k);}}
async function snap(name){await page.waitForTimeout(650);await page.screenshot({path:`${out}/${name}.png`});r.captures.push({name,position:await position(),fps:await page.evaluate(()=>__game.debugCounts.fps),viewport:page.viewportSize()});console.log('captured',name);}
async function orbit(dx){await page.mouse.move(605,178);await page.mouse.down();await page.mouse.move(605+dx,178,{steps:16});await page.mouse.up();await page.waitForTimeout(600);}
try{
 await page.goto('http://localhost:8080/');await page.locator('[data-action=start]').click({timeout:60000});await page.getByRole('button',{name:'Auto harvest',exact:true}).click();
 await walk(0,-4.4);await page.locator('#contextual-action-button').click();await page.locator('[data-destination="0"]').click();await page.waitForFunction(()=>__game.sectionRuntime.getActiveSectionId()==='section_1');
 await walk(.3,27);await snap('arrival-default');await walk(.3,23);await snap('approach-default');await orbit(195);await snap('approach-west-camera');await walk(3.4,23);await snap('ramp-entry');await walk(7.1,23);await snap('chest-closed-west-camera');
 await page.locator('#contextual-action-button').click();await page.waitForTimeout(1300);await snap('chest-open-west-camera');
 await orbit(-98);await snap('inside-quarter-one');await orbit(196);await snap('inside-quarter-two');
 await page.setViewportSize({width:390,height:844});await snap('inside-portrait');await page.setViewportSize({width:844,height:390});
 await walk(3.3,23);await walk(.3,23);await snap('exited');await walk(.3,30.8);await walk(11,30.8);await snap('tree-approach');await walk(11,30.1);
 r.treeBefore=await page.evaluate(()=>{const n=__game.resourceSystem.nodes.find(n=>n.id==='tree_section_1_arrival_r');return{chunks:n.state.remainingChunks,visible:n.group.visible};});await page.getByRole('button',{name:'Auto harvest',exact:true}).click();await page.waitForTimeout(9500);r.treeAfter=await page.evaluate(()=>{const n=__game.resourceSystem.nodes.find(n=>n.id==='tree_section_1_arrival_r');return{chunks:n.state.remainingChunks,visible:n.group.visible,player:{...__game.playerController.getState().pos}};});await snap('tree-after-native-auto');await page.getByRole('button',{name:'Auto harvest',exact:true}).click();
 await walk(14.5,30.8);await walk(14.5,24.5);await snap('rear-grounding');r.pack=await page.evaluate(()=>__game.frontierProgress.getInventoryState().pack);r.pass=true;
}catch(e){r.failure=String(e);r.failurePosition=await position().catch(()=>null);await page.screenshot({path:`${out}/failure.png`});console.error(e);process.exitCode=1;}finally{await fs.writeFile(`${out}/native-receipt.json`,JSON.stringify(r,null,2));console.log(JSON.stringify(r));await browser.close();}
