import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import * as THREE from '../vendor/three.module.js';
import { createWildkinMeshVisual } from '../src/world/wildkinMeshKit.js';
const close=(actual,expected)=>actual.length===expected.length&&actual.every((value,index)=>Math.abs(value-expected[index])<1e-7);
function closedAudit(mesh, expectedVertices, expectedTriangles) {const geometry=mesh.geometry,position=geometry.getAttribute('position'),index=geometry.getIndex();assert.ok(position&&index,`${mesh.name} is indexed`);assert.equal(position.count,expectedVertices);assert.equal(index.count/3,expectedTriangles);const edges=new Map();let volume=0;for(let i=0;i<index.count;i+=3){const tri=[index.getX(i),index.getX(i+1),index.getX(i+2)];for(let j=0;j<3;j++){const a=tri[j],b=tri[(j+1)%3],key=a<b?`${a}:${b}`:`${b}:${a}`;edges.set(key,(edges.get(key)||0)+1);}const a=tri[0]*3,b=tri[1]*3,c=tri[2]*3,p=position.array;volume+=(p[a]*(p[b+1]*p[c+2]-p[b+2]*p[c+1])+p[a+1]*(p[b+2]*p[c]-p[b]*p[c+2])+p[a+2]*(p[b]*p[c+1]-p[b+1]*p[c]))/6;}assert.ok([...edges.values()].every(count=>count===2),`${mesh.name} is closed`);assert.ok(Number.isFinite(volume)&&volume>1e-5,`${mesh.name} has positive outward signed volume`);}
function verticalSkin(torso,x,z){const ray=new THREE.Raycaster();ray.set(new THREE.Vector3(x,3,z),new THREE.Vector3(0,-1,0));const top=ray.intersectObject(torso,false)[0];ray.set(new THREE.Vector3(x,-2,z),new THREE.Vector3(0,1,0));const bottom=ray.intersectObject(torso,false)[0];assert.ok(top&&bottom,`torso receives contact ray at ${x},${z}`);return{top:top.point.y,bottom:bottom.point.y};}
test('Cinderjaw R2 consumes four V2-preserving 32-vertex limbs and twelve literal beveled shingles',()=>{const plan=JSON.parse(readFileSync(new URL('../docs/species/cinderjaw/anatomy-plan-r2.json',import.meta.url),'utf8'));const model=createWildkinMeshVisual('asset_cinderjaw');const limbs=model.children.filter(part=>part.name==='low_clawed_leg'),plates=model.children.filter(part=>part.name==='overlap_cara_tile');assert.equal(limbs.length,4);assert.equal(plates.length,12);assert.equal(model.children.filter(part=>part.name==='claw').length,4);for(let i=0;i<4;i++){closedAudit(limbs[i],32,60);assert.ok(close(Array.from(limbs[i].geometry.getAttribute('position').array),plan.limbs[i].vertices.flat()),`${plan.limbs[i].name} literal coordinates`);}for(let i=0;i<12;i++){closedAudit(plates[i],10,16);assert.ok(close(Array.from(plates[i].geometry.getAttribute('position').array),plan.plates[i].vertices.flat()),`shingle ${i} literal coordinates`);}assert.deepEqual(model.children.map(part=>part.name),['armored_reptile_torso','wide_armored_skull','broad_cream_jaw','low_clawed_leg','claw','low_clawed_leg','claw','low_clawed_leg','claw','low_clawed_leg','claw','inset_almond_eye','eye_glint','inset_almond_eye','eye_glint',...Array(12).fill('overlap_cara_tile'),'heavy_reptile_tail']);});
test('Cinderjaw R2 preserves V2 cap/claw contacts and measures every shingle against the actual torso',()=>{const plan=JSON.parse(readFileSync(new URL('../docs/species/cinderjaw/anatomy-plan-r2.json',import.meta.url),'utf8'));const model=createWildkinMeshVisual('asset_cinderjaw');model.updateMatrixWorld(true);const torso=model.children.find(part=>part.name==='armored_reptile_torso'),limbs=model.children.filter(part=>part.name==='low_clawed_leg'),claws=model.children.filter(part=>part.name==='claw'),plates=model.children.filter(part=>part.name==='overlap_cara_tile');for(let i=0;i<4;i++){const spec=plan.limbs[i],lowerY=spec.vertices[0][1];for(const shell of spec.upperRingShell){const skin=verticalSkin(torso,shell.x,shell.z);assert.ok(lowerY<=spec.commonCapInterval.capY&&spec.commonCapInterval.capY<=skin.top&&spec.commonCapInterval.capY>=skin.bottom,`${spec.name} upper cap remains inside actual torso shell`);}assert.ok(Math.abs(claws[i].position.x-spec.clawCenter[0])<1e-7&&Math.abs(claws[i].position.z-spec.clawCenter[2])<1e-7,`${spec.name} claw center retained`);assert.ok(claws[i].position.y+.14*.45>=lowerY,`${spec.name} claw overlaps ankle elevation`);assert.equal(limbs[i].geometry.getAttribute('position').count,32);}for(let i=0;i<12;i++){const spec=plan.plates[i],position=plates[i].geometry.getAttribute('position');for(let j=0;j<5;j++){const base=spec.baseProbes[j],top=spec.topProbes[j],skin=verticalSkin(torso,base.x,base.z);assert.ok(Math.abs(position.getY(j)-(base.y-spec.baseBurial))<1e-6,`shingle ${i} base burial ${j}`);assert.ok(position.getY(j)<=skin.top&&position.getY(j)>=skin.bottom,`shingle ${i} buried base contacts torso ${j}`);assert.ok(Math.abs(position.getY(5+j)-(top.y+top.clearance))<1e-6,`shingle ${i} top clearance ${j}`);}}});
test('Cinderjaw R2 preserves the other six code-native component orders for the browser snapshot parity gate',()=>{const baseline=JSON.parse(readFileSync(new URL('../art/reviews/cinderjaw/rotation-1/baseline-sibling-hashes.json',import.meta.url),'utf8'));for(const expected of baseline.species.filter(species=>species.id!=='asset_cinderjaw')){const model=createWildkinMeshVisual(expected.id),names=[];model.traverse(part=>{if(part.isMesh)names.push(part.name);});assert.deepEqual(names,expected.parts.map(part=>part.name),`${expected.id} component order`);}});