import { UPGRADE_CATALOG } from "../progression/upgradeCatalog.js";
import { createSkillTree } from "./skillTree.js";
import { iconMarkup, resourceLabel } from "./itemIcons.js";

const esc = (value = "") => String(value).replace(/[&<>\"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&#39;" }[c]));
const label = (id) => resourceLabel(id);
const icon = (id, options = {}) => iconMarkup(id, options);
const effect = (modifiers = {}) => Object.entries(modifiers).map(([key, value]) => {
  if (key === "maxHealthBonus") return `+${value} health`;
  if (key === "captureCapacity") return `carry ${value} bonds`;
  if (key.includes("DamageMultiplier")) return `+${Math.round((value - 1) * 100)}% tool power`;
  if (key.includes("YieldMultiplier")) return `+${Math.round((value - 1) * 100)}% harvest`;
  if (key === "pickupMagnetRadius") return `reach ${value}m`;
  if (key === "medkitHeal") return `medkits heal ${value}`;
  return `${key} ${value}`;
}).join(" · ");

export function createBetaShell({ app, getModel, onAction = () => null, onBlockingChanged = () => {}, canOpen = () => true } = {}) {
  if (!app) return { update() {}, open() {}, close() {}, isOpen: () => false, showWelcome() {}, toast() {}, destroy() {} };
  const root = document.createElement("div"); root.id = "beta-shell"; root.setAttribute("aria-live", "polite");
  const modal = document.createElement("section"); modal.className = "beta-modal"; modal.hidden = true;
  const hud = document.createElement("div"); hud.className = "beta-hud";
  hud.innerHTML = `<div class="beta-objective"></div><div class="beta-hud-actions"><button class="beta-hud-button" data-action="open" data-tab="inventory" aria-label="Open backpack">${icon("backpack")}<b class="beta-cargo-count">0</b></button><button class="beta-hud-button beta-skill-button" data-action="open" data-tab="skills" aria-label="Open skill paths">${icon("skills")}<b class="beta-skill-count">0</b></button></div><div class="beta-quick"><button data-action="ability" class="beta-ability">${icon("paw")}<span class="ability-label">ABILITY</span></button><button data-action="heal" class="beta-heal">${icon("medkit")}<small>0</small></button></div>`;
  const toastEl = document.createElement("div"); toastEl.className = "beta-toast"; toastEl.hidden = true;
  root.append(hud, modal, toastEl); app.appendChild(root);
  let opened = false, welcome = false, activeTab = "journal", inventoryTab = "carried", selectedItem = null, selectedSkill = null, lastUpdate = 0, signature = "", toastTimer = 0, pendingImport = null;
  root.addEventListener("pointerdown", (event) => event.stopPropagation()); root.addEventListener("touchstart", (event) => event.stopPropagation(), { passive: true });
  const setBlocking = (value) => onBlockingChanged(!!value);
  const focusModal = () => requestAnimationFrame(() => modal.querySelector("button,input")?.focus());
  function result(action, payload) {
    const response = onAction(action, payload);
    const complete = (resolved) => { const message = typeof resolved === "string" ? resolved : resolved?.message; if (message) toast(resolved?.ok === false ? "Not yet" : "Frontier", message); render(true); };
    if (response?.then) { response.then(complete).catch(() => toast("Restore failed", "That save could not be restored.")); return; }
    complete(response); return response;
  }
  function open(tab = "journal") { if (!canOpen()) return false; welcome = false; opened = true; activeTab = tab; modal.hidden = false; root.classList.add("is-open"); setBlocking(true); signature = ""; render(true); focusModal(); return true; }
  function close() { if (modal.contains(document.activeElement)) document.activeElement.blur(); pendingImport = null; welcome = false; opened = false; modal.hidden = true; root.classList.remove("is-open", "is-welcome"); setBlocking(false); }
  function isOpen() { return opened || welcome; }
  function showWelcome() { welcome = true; opened = false; modal.hidden = false; root.classList.add("is-open", "is-welcome"); setBlocking(true); render(true); focusModal(); }
  function toast(title, detail = "") { toastEl.innerHTML = `<strong>${esc(title)}</strong><span>${esc(detail)}</span>`; toastEl.hidden = false; toastEl.classList.add("show"); clearTimeout(toastTimer); toastTimer = setTimeout(() => { toastEl.classList.remove("show"); toastEl.hidden = true; }, 2400); }
  function itemGrid(items, values) { return `<div class="item-grid">${items.map((id) => { const count = Math.max(0, Number(values?.[id]) || 0); return `<button data-resource-id="${esc(id)}" class="item-slot ${selectedItem === id ? "is-selected" : ""}" aria-label="${esc(label(id))}: ${count}">${icon(id)}<b>${count}</b></button>`; }).join("")}</div>`; }
  function inventoryPanel(model) {
    const carried = model.cargo ?? {}, stored = model.progress?.bankedResources ?? {};
    const values = inventoryTab === "carried" ? carried : stored;
    const ids = [...new Set([...Object.keys(stored), ...Object.keys(carried)])];
    const active = selectedItem && ids.includes(selectedItem) ? selectedItem : (ids.find((id) => (values[id] ?? 0) > 0) ?? ids[0]);
    selectedItem = active ?? null;
    const count = active ? Math.max(0, Number(values[active]) || 0) : 0;
    const source = inventoryTab === "carried" ? "At risk until you extract." : "Secured at Camp. Spend it in Workshop.";
    return `<section class="backpack-panel"><div class="panel-title"><div>${icon("backpack")}<div><p class="beta-kicker">FIELD PACK</p><h2>Backpack</h2></div></div><span>${inventoryTab === "carried" ? "AT RISK" : "SECURED"}</span></div><div class="segment"><button data-inventory-tab="carried" class="${inventoryTab === "carried" ? "active" : ""}">CARRIED</button><button data-inventory-tab="stored" class="${inventoryTab === "stored" ? "active" : ""}">STORED</button></div>${itemGrid(ids, values)}${active ? `<article class="item-detail">${icon(active)}<div><p class="beta-kicker">${inventoryTab === "carried" ? "EXPEDITION ITEM" : "CAMP STORE"}</p><h3>${esc(label(active))}</h3><strong>${count}</strong><p>${source}</p></div></article>` : `<p class="beta-empty">Gather materials on an expedition, then extract to secure them.</p>`}</section>`;
  }
  function workshop(model) {
    const bank = model.progress?.bankedResources ?? {};
    return model.isCamp ? `<section class="workshop-panel"><div class="panel-title"><div>${icon("axe")}<div><p class="beta-kicker">MATTER RESONATOR</p><h2>Workshop</h2></div></div></div><p class="panel-intro">Spend secured materials to strengthen each expedition.</p><div class="workshop-store">${Object.keys(bank).map((id) => `<span>${icon(id)}<b>${bank[id] || 0}</b></span>`).join("")}</div>${UPGRADE_CATALOG.map((upgrade) => { const current = model.progress?.upgrades?.[upgrade.id] ?? 0; const tier = upgrade.tiers[current]; const levelLocked = tier && (model.playerLevel ?? 1) < tier.minPlayerLevel; const cost = Object.entries(tier?.cost ?? {}); const available = tier && !levelLocked && cost.every(([id, amount]) => (bank[id] ?? 0) >= amount); return `<article class="upgrade-card ${!tier ? "is-max" : ""}"><div class="upgrade-card__mark">${icon(upgrade.id === "vitality" ? "shield" : upgrade.id === "field_tool" ? "axe" : upgrade.id === "capture_capacity" ? "paw" : upgrade.id === "field_medicine" ? "medkit" : "skills")}</div><div><p class="beta-kicker">${current}/${upgrade.tiers.length} TIER</p><h3>${esc(upgrade.displayName)}</h3><em>${tier ? esc(effect(tier.modifiers)) : "Fully synchronized"}</em>${tier ? `<div class="cost-row">${cost.map(([id, amount]) => `<span class="${(bank[id] ?? 0) >= amount ? "met" : ""}">${icon(id)}${amount}</span>`).join("")}<small>LV ${tier.minPlayerLevel}</small></div>` : ""}</div>${tier ? `<button data-action="purchaseUpgrade" data-id="${esc(upgrade.id)}" ${available ? "" : "disabled"}>SYNC</button>` : ""}</article>`; }).join("")}<button class="craft-button" data-action="craftMedkit">${icon("medkit")} CRAFT MEDKIT <span>${icon("fiber")}3 ${icon("berries")}2</span></button></section>` : `<section class="beta-locked"><div>${icon("skills")}</div><p class="beta-kicker">CAMP SYSTEM</p><h2>Workshop at Camp</h2><p>Extract to Camp before spending secured matter.</p></section>`;
  }
  function companionPanel(model) { const companions = model.companions ?? []; const selected = companions.find((c) => c.id === selectedItem) ?? companions.find((c) => c.active) ?? companions[0]; return `<section class="wildkin-panel"><div class="panel-title"><div>${icon("paw")}<div><p class="beta-kicker">FIELD BONDS</p><h2>Wildkin</h2></div></div><span>${(model.pendingCompanions ?? []).length}/${model.captureCapacity ?? 1}</span></div><div class="wildkin-list">${companions.map((c) => `<button data-companion-id="${esc(c.id)}" class="wildkin-chip ${selected?.id === c.id ? "is-selected" : ""} ${c.secured ? "is-secured" : ""}" style="--wildkin:${esc(c.color || "#36c896")}">${icon(c.id, { size: 30, label: c.name })}<span>${esc(c.name)}</span>${c.secured ? "<b>✓</b>" : ""}</button>`).join("")}</div>${selected ? `<article class="wildkin-detail" style="--wildkin:${esc(selected.color || "#36c896")}">${icon(selected.id, { size: 50, label: selected.name })}<div><p class="beta-kicker">${selected.secured ? selected.active ? "ACTIVE COMPANION" : "SECURED AT CAMP" : selected.pending ? "UNSECURED — EXTRACT" : selected.discovered ? "OBSERVED" : "UNKNOWN SIGNAL"}</p><h3>${esc(selected.name)}</h3><p>${esc(selected.secured ? selected.abilityDescription : selected.habitat || "Follow its frontier signal.")}</p></div>${selected.secured ? `<button data-action="selectCompanion" data-id="${esc(selected.id)}">${selected.active ? "ACTIVE" : "SELECT"}</button>` : ""}</article>` : ""}</section>`; }
  function journal(model) { return `<section class="journal-panel"><p class="beta-kicker">NEXT EXPEDITION</p><h2>${esc(model.objective?.title || "Answer the frontier call")}</h2><p>${esc(model.objective?.description || "Step through the gate and bring something home.")}</p><button class="beta-gold-button" data-action="openMap">${icon("map")} OPEN MAP</button><div class="journal-stats"><span><b>LV ${model.playerLevel ?? 1}</b> FRONTIER</span><span><b>${model.bankedXp ?? 0}</b> SECURED XP</span></div></section>`; }
  function settings(model) { return `<section class="settings-panel"><p class="beta-kicker">EXPEDITION SETTINGS</p><h2>Settings</h2><label><span>Sound</span><input data-action="mute" type="checkbox" ${model.settings?.muted ? "" : "checked"}></label><label><span>Reduced motion</span><input data-action="reducedMotion" type="checkbox" ${model.settings?.reducedMotion ? "checked" : ""}></label><div class="controls-card"><b>CONTROLS</b><p>WASD move · Shift run · C sneak · Space dodge</p><p>F / hold tool · E interact · Q ability · H medkit</p><p>B backpack · K skills · M map</p></div><button data-action="exportSave">EXPORT SAVE</button>${pendingImport ? `<div class="restore-card"><strong>Restore ${esc(pendingImport.name)}?</strong><p>This replaces the current Camp save.</p><button data-action="cancel-import">CANCEL</button><button data-action="confirm-import">RESTORE</button></div>` : `<label class="beta-import">RESTORE SAVE<input data-action="import-save" type="file" accept="application/json,.json"></label>`}</section>`; }
  function body(model) {
    if (welcome) return `<div class="beta-welcome"><div class="beta-emblem">${icon("paw")}</div><p class="beta-kicker">SUNLIT WILDS</p><h1>WILDKIN<br><span>FRONTIER</span></h1><p>Gather. Bond. Bring the frontier home.</p><button class="beta-gold-button" data-action="start">${model.progress?.hasDepartedOnce ? "CONTINUE" : "ENTER FRONTIER"}</button><button class="beta-link" data-action="open" data-tab="settings">Settings</button></div>`;
    const tabs = [["journal", "MAP"], ["inventory", "PACK"], ["workshop", "WORK"], ["skills", "SKILLS"], ["wildkin", "WILDKIN"], ["settings", "···"]].map(([id, name]) => `<button class="${activeTab === id ? "active" : ""}" data-tab="${id}">${id === "inventory" ? icon("backpack") : id === "skills" ? icon("skills") : id === "wildkin" ? icon("paw") : ""}<span>${name}</span></button>`).join("");
    const panel = activeTab === "inventory" ? inventoryPanel(model) : activeTab === "workshop" ? workshop(model) : activeTab === "skills" ? createSkillTree({ skills: model.skills ?? {}, iconMarkup: icon, selectedId: selectedSkill }) : activeTab === "wildkin" ? companionPanel(model) : activeTab === "settings" ? settings(model) : journal(model);
    return `<div class="beta-panel" role="dialog" aria-modal="true" aria-label="Wildkin Frontier menu"><header><div><p>WILDKIN FRONTIER</p><strong>${esc(model.regionName || "Camp")}</strong></div><button class="beta-close" data-action="close" aria-label="Close">×</button></header><nav>${tabs}</nav><main>${panel}</main></div>`;
  }
  function render(force = false) { const model = getModel?.() ?? {}; const next = JSON.stringify({ welcome, opened, activeTab, inventoryTab, selectedItem, selectedSkill, pendingImport: pendingImport?.name, camp: model.isCamp, region: model.regionName, cargo: model.cargo, xp: model.bankedXp, progress: model.progress, skills: model.skills, companions: model.companions, settings: model.settings }); if (force || next !== signature) { signature = next; modal.innerHTML = body(model); } const objective = hud.querySelector(".beta-objective"); if (objective) objective.innerHTML = `<small>${esc(model.regionName || "CAMP")}</small><strong>${esc(model.objective?.title || "Find the frontier signal")}</strong>`; hud.querySelector(".beta-heal small").textContent = model.medkits ?? 0; hud.querySelector(".beta-cargo-count").textContent = Object.values(model.cargo ?? {}).reduce((sum, count) => sum + (Number(count) || 0), 0); hud.querySelector(".beta-skill-count").textContent = model.skills?.points ?? 0; const ability = hud.querySelector(".beta-ability"); ability.disabled = !model.ability?.ready || model.isCamp; ability.dataset.cooldown = !model.isCamp && model.ability && !model.ability.ready ? Math.ceil(model.ability.cooldown || 0) : ""; ability.setAttribute("aria-label", model.ability?.name ?? "Companion ability"); const activeCompanion = (model.companions ?? []).find((companion) => companion.active); ability.querySelector(".item-icon")?.replaceWith(document.createRange().createContextualFragment(icon(activeCompanion?.id ?? "paw", { size: 32, label: activeCompanion?.name ?? "Companion ability" }))); ability.querySelector(".ability-label").textContent = !model.ability ? "ABILITY" : model.ability.ready ? model.ability.name : `${model.ability.name} ${Math.ceil(model.ability.cooldown || 0)}s`; }
  root.addEventListener("click", (event) => { const item = event.target.closest("[data-resource-id],[data-skill-id],[data-companion-id],button"); if (!item) return; event.preventDefault(); if (item.dataset.resourceId) { selectedItem = item.dataset.resourceId; render(true); return; } if (item.dataset.skillId) { selectedSkill = item.dataset.skillId; render(true); return; } if (item.dataset.companionId) { selectedItem = item.dataset.companionId; render(true); return; } const action = item.dataset.action; if (action === "open") { open(item.dataset.tab || "journal"); return; } if (item.dataset.tab) { activeTab = item.dataset.tab; render(true); return; } if (action === "close") { close(); return; } if (action === "start") { result("start"); close(); return; } if (action === "cancel-import") { pendingImport = null; render(true); return; } if (action === "confirm-import") { const file = pendingImport; pendingImport = null; result("import-save", file); render(true); return; } if (action === "selectCompanion") result(action, item.dataset.id || null); else if (action) result(action, item.dataset.id); render(true); });
  root.addEventListener("click", (event) => { const tab = event.target.closest("[data-inventory-tab]")?.dataset.inventoryTab; if (tab) { inventoryTab = tab; render(true); } });
  root.addEventListener("change", (event) => { const action = event.target.dataset.action; if (action === "import-save") { pendingImport = event.target.files?.[0] ?? null; event.target.value = ""; render(true); return; } if (action) result(action, action === "mute" ? !event.target.checked : event.target.checked); });
  const keydown = (event) => { if (event.defaultPrevented) return; if (event.key === "Escape" && !event.repeat) { if (!isOpen() && !canOpen()) return; event.preventDefault(); isOpen() ? close() : open(); return; } if (event.key === "Tab" && isOpen()) { const controls = [...modal.querySelectorAll("button:not([disabled]),input:not([disabled])")]; if (!controls.length) return; const first = controls[0], last = controls.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } };
  window.addEventListener("keydown", keydown); function update() { const now = performance.now(); if (now - lastUpdate < 200) return; lastUpdate = now; render(false); }
  return { update, open, close, isOpen, getState: () => ({ open: opened, welcome, tab: activeTab }), showWelcome, toast, destroy() { clearTimeout(toastTimer); window.removeEventListener("keydown", keydown); root.remove(); } };
}
