import fs from 'node:fs';import {chromium} from 'playwright';
const b=await chromium.launch({headless:true,channel:'msedge'}),p=await b.newPage({viewport:{width:412,height:915}}),out='art/reviews/skybreak-tablelands/rotation-1';const save=JSON.parse(fs.readFileSync('.dream-loop/heartwood-circuit/original-save-private.json'));
await p.addInitScript(s=>localStorage.setItem('wildkin.frontierProgress',JSON.stringify(s.progress)),save);const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8080/');await p.waitForFunction(()=>window.__game?.frontierChunks);await p.locator('[data-action=start]').click();
async function place(x,z){await p.evaluate(({x,z})=>{const g=window.__game;g.frontierChunks.update({x,z},{activeSectionId:'camp'});g.characterPhysics.setPosition({x,y:g.frontierChunks.getHeight(x,z)+.7,z});g.playerController.syncPosFromPhysics();g.playerController.snapRenderPose();g.cameraFollow.orbitBy(-g.cameraFollow.getYaw());g.cameraFollow.snap();},{x,z});await p.waitForTimeout(2200);}
const snap=()=>p.evaluate(()=>{const g=window.__game,pose={...g.playerController.getState().pos},surfaces=g.physicsWorld.staticColliders.map(c=>g.physicsWorld.getColliderSurfaceId(c)).filter(id=>id?.includes(':skybreak:rock:'));const hit=g.characterPhysics.castRay({x:pose.x,y:pose.y+.1,z:pose.z},{x:0,y:-1,z:0},4);return {pose,health:g.playerCombat.getHealth(),surfaces,groundHit:hit?{point:hit.point,normal:hit.normal,id:g.physicsWorld.getColliderSurfaceId(hit.collider)}:null};});
await place(20,-222.8);const before=await snap();await p.screenshot({path:out+'/contact-before.png'});await p.keyboard.down('w');await p.waitForTimeout(2000);await p.keyboard.up('w');const against=await snap();await p.screenshot({path:out+'/contact-against.png'});
await p.keyboard.down('s');await p.waitForTimeout(2000);await p.keyboard.up('s');const retreat=await snap();await p.screenshot({path:out+'/contact-retreat.png'});
const rays=await p.evaluate(()=>{const g=window.__game,result=[];for(let x=18.5;x<=21.5;x+=.25)for(let z=-227;z<=-224.5;z+=.25){const hit=g.characterPhysics.castRay({x,y:39,z},{x:0,y:-1,z:0},15);if(hit&&g.physicsWorld.getColliderSurfaceId(hit.collider)?.includes(':skybreak:rock:'))result.push({x,z,y:hit.point.y,normal:hit.normal,id:g.physicsWorld.getColliderSurfaceId(hit.collider)});}return result;});
await place(400,400);const away=await snap();await place(20,-222.8);const returned=await snap();
fs.writeFileSync(out+'/contact-proof.json',JSON.stringify({fixture:'Diagnostic supported start near new face, ordinary W approach/S retreat; separate diagnostic streaming moves. Not a whole ordinary circuit.',before,against,retreat,away,returned,rays,errors},null,2));await b.close();console.log(JSON.stringify({before,against,retreat,awayCount:away.surfaces.length,returnedCount:returned.surfaces.length,rockRayHits:rays.length,errors}));
