import fs from 'node:fs';
import {chromium} from 'playwright';
const out='art/reviews/skybreak-tablelands/rotation-1/kit';
const b=await chromium.launch({headless:true,channel:'msedge'}),p=await b.newPage({viewport:{width:412,height:915},deviceScaleFactor:1});
const save=JSON.parse(fs.readFileSync('.dream-loop/heartwood-circuit/original-save-private.json'));
await p.addInitScript(s=>localStorage.setItem('wildkin.frontierProgress',JSON.stringify(s.progress)),save);
await p.goto('http://localhost:8080/');await p.waitForFunction(()=>window.__game?.frontierChunks);await p.locator('[data-action=start]').click();
const poses=[{name:'arrival',x:4,z:-153,yaw:0},{name:'ascent',x:-7,z:-184,yaw:Math.atan2(-12,20)},{name:'crown',x:12,z:-228,yaw:Math.atan2(-20,-14)},{name:'return',x:36,z:-188,yaw:Math.PI}];
const specs=[{name:'embedded-buttress-a',asset:'asset_verdant_cliff_buttress',x:20,z:-226,scale:.65,yaw:.4,baseX:19.3369,baseZ:-224.99},{name:'embedded-buttress-b',asset:'asset_verdant_cliff_buttress',x:28,z:-220,scale:.65,yaw:.4,baseX:29.1349,baseZ:-220.1446}];
await p.evaluate(async specs=>{const g=window.__game,{default:w}=await import('/src/world/data/world.js'),{createVisualAssetVisual}=await import('/src/world/visualFactory.js');for(const s of specs){const v=createVisualAssetVisual(w.visualAssets.find(a=>a.id===s.asset));v.position.set(s.x,g.frontierChunks.getHeight(s.baseX,s.baseZ),s.z);v.rotation.y=s.yaw;v.scale.setScalar(s.scale);g.scene.add(v);}},specs);
const result=[];
for(const pose of poses){await p.evaluate(p=>{const g=window.__game;g.characterPhysics.setPosition({x:p.x,y:g.frontierChunks.getHeight(p.x,p.z)+.7,z:p.z});g.playerController.syncPosFromPhysics();g.playerController.snapRenderPose();g.cameraFollow.orbitBy(p.yaw-g.cameraFollow.getYaw());g.cameraFollow.snap();},pose);await p.waitForTimeout(6500);
result.push(await p.evaluate(async({pose,specs})=>{const g=window.__game,T=g.THREE,{default:w}=await import('/src/world/data/world.js'),{createVisualAssetVisual}=await import('/src/world/visualFactory.js');g.camera.updateMatrixWorld();
function projected(points){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity,central=0,front=0;for(const point of points){const v=point.clone().project(g.camera),x=(v.x+1)*206,y=(1-v.y)*457.5;minX=Math.min(x,minX);minY=Math.min(y,minY);maxX=Math.max(x,maxX);maxY=Math.max(y,maxY);if(v.z>=-1&&v.z<=1){front++;if(x>=0&&x<=412&&y>=160&&y<=640)central++;}}return {minX,minY,maxX,maxY,central,front,total:points.length};}
return {pose,camera:g.camera.position.toArray(),direction:g.camera.getWorldDirection(new T.Vector3()).toArray(),probes:specs.map(s=>{const a=w.visualAssets.find(a=>a.id===s.asset),v=createVisualAssetVisual(a),baseY=g.frontierChunks.getHeight(s.baseX,s.baseZ);v.position.set(s.x,baseY,s.z);v.rotation.y=s.yaw;v.scale.setScalar(s.scale);v.updateMatrixWorld(true);const points=[];v.traverse(o=>{if(o.isMesh){const pos=o.geometry.attributes.position;for(let i=0;i<pos.count;i++)points.push(new T.Vector3().fromBufferAttribute(pos,i).applyMatrix4(o.matrixWorld));}});const hull=[];for(let i=0;i<a.collision.vertices.length;i+=3)hull.push(new T.Vector3(...a.collision.vertices.slice(i,i+3)).multiplyScalar((a.model.scale??1)*s.scale).applyAxisAngle(new T.Vector3(0,1,0),s.yaw).add(v.position));return {...s,baseY,mesh:projected(points),hull:projected(hull)};})};},{pose,specs}));await p.screenshot({path:out+'/embedded-preview-'+pose.name+'.png'});}
fs.writeFileSync(`${out}/cliff-projections-embedded.json`,JSON.stringify({note:'Actual camera, complete mesh and convex hull projection of diagnostic models without physics or resident lifecycle. Central window y160..640 approximate HUD safety; not occlusion/collision proof.',views:result},null,2));await b.close();console.log(JSON.stringify(result.map(v=>({pose:v.pose.name,camera:v.camera,probes:v.probes.map(p=>({name:p.name,screen:p.mesh}))}))));
