import fs from 'node:fs';
import {chromium} from 'playwright';
const out='art/reviews/skybreak-tablelands/rotation-1', b=await chromium.launch({headless:true,channel:'msedge'}),p=await b.newPage({viewport:{width:412,height:915}});
const save=JSON.parse(fs.readFileSync('.dream-loop/heartwood-circuit/original-save-private.json')),errors=[];
await p.addInitScript(s=>{if(!localStorage.getItem('wildkin.frontierProgress'))localStorage.setItem('wildkin.frontierProgress',JSON.stringify(s.progress));},save);
p.on('pageerror',e=>errors.push(e.message));
await p.goto('http://localhost:8080/');await p.waitForFunction(()=>window.__game?.frontierChunks);await p.locator('[data-action=start]').click();
await p.evaluate(()=>{const g=window.__game,x=30.2,z=-214;g.frontierChunks.update({x,z},{activeSectionId:'camp'});g.characterPhysics.setPosition({x,y:g.frontierChunks.getHeight(x,z)+.7,z});g.playerController.syncPosFromPhysics();g.playerController.snapRenderPose();g.cameraFollow.orbitBy(-g.cameraFollow.getYaw());g.cameraFollow.snap();});await p.waitForTimeout(2500);
const snap=()=>p.evaluate(()=>{const g=window.__game;return {pos:{...g.playerController.getState().pos},pack:g.frontierProgress.getState().inventory.pack,eligible:g.resourceSystem.getManualTargets(g.playerController.getState().pos).map(t=>({id:t.id,remaining:t.state.remainingChunks,resourceId:t.type.resourceId})),pending:g.pickupSystem.getPendingYields(),pickups:g.pickupSystem.getPickups().map(v=>({id:v.resourceId,state:v.state,age:v.age,pos:{x:v.mesh.position.x,y:v.mesh.position.y,z:v.mesh.position.z}}))};});
const r={fixture:'Isolated earned-save copy, diagnostic supported start beside exact crystal; ordinary F and movement only after placement. No inventory grants.',before:await snap(),samples:[],errors};
await p.keyboard.down('f');for(let i=0;i<16;i++){await p.waitForTimeout(250);r.samples.push(await snap());}await p.keyboard.up('f');await p.waitForTimeout(2000);r.afterWait=await snap();await p.screenshot({path:out+'/reward-witness-wait.png'});
// The physics ejection direction varies. Guide ordinary controls toward the actual visible drop.
r.approach=[];for(let step=0;step<80;step++){const s=await snap();r.approach.push(s);const drop=s.pickups.find(v=>v.id==='crystal_shard');if(!drop)break;const dx=drop.pos.x-s.pos.x,dz=drop.pos.z-s.pos.z,keys=[];if(Math.abs(dx)>.18)keys.push(dx>0?'d':'a');if(Math.abs(dz)>.18)keys.push(dz>0?'s':'w');for(const k of keys)await p.keyboard.down(k);await p.waitForTimeout(100);for(const k of keys)await p.keyboard.up(k);}await p.waitForTimeout(2500);r.afterApproach=await snap();await p.screenshot({path:out+'/reward-witness-approach.png'});
await p.waitForTimeout(3500);const before=await p.evaluate(()=>window.__game.frontierProgress.exportSave().payload.progress);await p.reload();await p.waitForFunction(()=>window.__game?.frontierChunks);await p.locator('[data-action=start]').click();await p.waitForTimeout(1500);const after=await p.evaluate(()=>window.__game.frontierProgress.exportSave().payload.progress);r.reloadExact=JSON.stringify(before)===JSON.stringify(after);r.inventoryReloadExact=JSON.stringify(before.inventory)===JSON.stringify(after.inventory);r.ecologyReloadExact=JSON.stringify(before.ecology)===JSON.stringify(after.ecology);r.afterReload=await snap();
fs.writeFileSync(out+'/reward-witness.json',JSON.stringify(r,null,2));await b.close();console.log(JSON.stringify({before:r.before,afterWait:r.afterWait,afterApproach:r.afterApproach,reloadExact:r.reloadExact,errors}));
