"""Tidefin neutral study. Authored closed topology, not image-to-3D. Game coordinates X/Y/Z; +Z forward."""
import argparse,sys,json,math,hashlib
from pathlib import Path
import bpy,bmesh
from mathutils import Vector
from mathutils.bvhtree import BVHTree
p=argparse.ArgumentParser();p.add_argument('--output-dir',required=True);p.add_argument('--primary-only',action='store_true');options=p.parse_args(sys.argv[sys.argv.index('--')+1:]);out=Path(options.output_dir).resolve();out.mkdir(parents=True,exist_ok=True)
assert not(out/'tidefin.glb').exists(),'Preserve existing study'
bpy.ops.wm.read_factory_settings(use_empty=True)
C={'blue':(31,65,104),'blueLight':(38,76,117),'blueShade':(30,59,93),'blueDeep':(25,50,81),'belly':(117,155,147),'bellyLight':(140,174,158),'bellyShade':(101,137,132),'cyan':(51,137,143),'cyanLight':(70,158,161),'cyanShade':(40,117,130),'ivory':(211,198,166),'ivoryLight':(226,211,181),'ivoryShade':(177,169,142),'eye':(22,19,15),'glint':(239,229,204),'socket':(112,96,66)}
keys=list(C)
# Generated byte PNG is written directly; use intended sRGB bytes, not twice-dark linear values.
def lin(v):return v/255
atlas=bpy.data.images.new('Tidefin matte atlas256',width=256,height=256,alpha=False);pixels=[]
for y in range(256):
 for x in range(256):pixels.extend([lin(v)for v in C[keys[y//64*4+x//64]]]+[1])
atlas.pixels.foreach_set(pixels);atlas.filepath_raw=str(out/'tidefin-palette.png');atlas.file_format='PNG';atlas.save();atlas.pack()
mat=bpy.data.materials.new('Tidefin matte palette');mat.use_nodes=True;n=mat.node_tree.nodes;bs=n['Principled BSDF'];bs.inputs['Roughness'].default_value=1;bs.inputs['Metallic'].default_value=0;bs.inputs['Specular IOR Level'].default_value=0;t=n.new('ShaderNodeTexImage');t.image=atlas;t.interpolation='Closest';mat.node_tree.links.new(t.outputs['Color'],bs.inputs['Base Color'])
groups={'TidefinBody':[],'TidefinFeatures':[]}
def mesh(name,v,f,colors,group='TidefinFeatures',refine=False):
 data=bpy.data.meshes.new(name);data.from_pydata([(x,-z,y)for x,y,z in v],[],f);data.update();data.materials.append(mat)
 uv=data.uv_layers.new()
 for i,poly in enumerate(data.polygons):
  idx=keys.index(colors[i%len(colors)]);poly.use_smooth=False
  for k in poly.loop_indices:uv.data[k].uv=((idx%4+.5)/4,(idx//4+.5)/4)
 bm=bmesh.new();bm.from_mesh(data)
 if refine:bmesh.ops.subdivide_edges(bm,edges=list(bm.edges),cuts=1,use_grid_fill=True)
 bmesh.ops.recalc_face_normals(bm,faces=list(bm.faces));bad=sum(not e.is_manifold for e in bm.edges);assert bad==0,(name,bad);bm.to_mesh(data);bm.free()
 ob=bpy.data.objects.new(name,data);bpy.context.collection.objects.link(ob);groups[group].append(ob);return ob
# One continuous tail/paddle/pelvis/ribcage/neck/skull/muzzle loft, no yawed head shell.
# z,centerY,halfWidth,halfHeight. Loop locations also define four explicit limb openings.
profile=[(-1.58,1.12,.07,.19),(-1.53,1.12,.19,.29),(-1.39,1.08,.23,.30),(-1.27,.91,.16,.19),(-1.12,.84,.15,.115),(-.98,.80,.21,.15),(-.81,.79,.30,.23),(-.70,.79,.37,.30),(-.60,.80,.41,.33),(-.45,.82,.45,.34),(-.25,.86,.405,.28),(0,.875,.44,.32),(.20,.90,.51,.41),(.38,.97,.53,.40),(.55,1.03,.515,.38),(.72,1.06,.50,.37),(.86,1.045,.46,.32),(1.00,1.01,.36,.255),(1.13,.96,.27,.18),(1.19,.925,.20,.145)]
N=24;v=[];f=[];colors=[]
for i,(z,y,rx,ry)in enumerate(profile):
 for j in range(N):
  q=2*math.pi*j/N
  # Broad continuous planes, symmetrical skull and body. No random sphere scatter.
  if i>=17:
   # Connected blunt eight-plane muzzle: broad bridge and narrower chin, not an oval disc.
   contour=[(1,.10),(.70,.84),(0,.87),(-.70,.84),(-1,.10),(-.58,-.80),(0,-1),(.58,-.80)]
   aa=contour[j//3];bb=contour[(j//3+1)%8];tt=(j%3)/3
   xx=aa[0]*(1-tt)+bb[0]*tt;yy=aa[1]*(1-tt)+bb[1]*tt
   v.append((rx*xx,y+ry*yy,z+(.018*yy if i==19 else 0)))
  else:
   # Unequal axial facet planes break the previous perfectly parallel barrel bands.
   shift=({10:-.13,11:.11,12:-.065}.get(i,0))
   qq=q+shift*math.sin(q)
   v.append((rx*math.cos(qq),y+ry*math.sin(qq),z))
f.append(tuple(reversed(range(N))));colors.append('cyan')
holes=[(8,10,{22,23,0,1}),(8,10,{10,11,12,13}),(12,14,{22,23,0,1}),(12,14,{10,11,12,13})]
for i in range(len(profile)-1):
 for j in range(N):
  if any(lo<=i<hi and j in js for lo,hi,js in holes):continue
  f.append((i*N+j,i*N+(j+1)%N,(i+1)*N+(j+1)%N,(i+1)*N+j))
  yy=math.sin((j+.5)*2*math.pi/N)
  if i>=18:color='ivoryLight'if yy>.2 else'ivory'
  elif i<=1:color='cyanLight'if yy<.2 else'blueLight'
  elif yy<-.35:color='bellyLight'if yy<-.8 else'belly'
  else:color='blueLight'if yy>.6 else'blue'
  colors.append(color)
f.append(tuple(range((len(profile)-1)*N,len(profile)*N)));colors.append('ivory')
# Find actual four mesh-boundary loops and continue each into a planted paw.
edges={}
for face in f:
 for u,w in zip(face,face[1:]+face[:1]):
  key=tuple(sorted((u,w)));edges[key]=edges.get(key,0)+1
adj={}
for(u,w),count in edges.items():
 if count==1:adj.setdefault(u,[]).append(w);adj.setdefault(w,[]).append(u)
loops=[];remaining=set(adj)
while remaining:
 start=min(remaining);loop=[start];prev=None;cur=start
 while True:
  nxt=next(x for x in adj[cur]if x!=prev)
  if nxt==start:break
  loop.append(nxt);prev,cur=cur,nxt
 remaining.difference_update(loop);loops.append(loop)
assert len(loops)==4 and all(len(loop)==12 for loop in loops)
landmarks={'pelvis':[0,.80,-.45],'chest':[0,.88,.20],'neck':[0,1.03,.55],'head':[0,1.06,.72],'tailBase':[0,.79,-.81]};soles=[]
for loop in loops:
 center=sum((Vector(v[i])for i in loop),Vector())/len(loop);sgn=1 if center.x>0 else-1;fore=center.z>0;label=('Left'if sgn>0 else'Right')+('Fore'if fore else'Hind')
 source_angles=[math.atan2((v[i][2]-center.z)/.18,(v[i][1]-center.y)/.22)for i in loop]
 angle_candidates=[[sign*2*math.pi*j/12+shift*math.pi/6 for j in range(12)]for sign in [-1,1]for shift in range(12)]
 angles=min(angle_candidates,key=lambda aa:sum(abs(math.atan2(math.sin(x-y),math.cos(x-y)))for x,y in zip(aa,source_angles)))
 chain=([(sgn*.43,.93,.36,.16,.19),(sgn*.49,.79,.355,.225,.25),(sgn*.52,.62,.32,.225,.245),(sgn*.53,.46,.34,.17,.19),(sgn*.52,.31,.42,.125,.14),(sgn*.52,.19,.48,.13,.15),(sgn*.52,.13,.52,.21,.255),(sgn*.52,.055,.535,.215,.265),(sgn*.52,0,.535,.21,.265)]if fore else[(sgn*.43,.87,-.47,.175,.21),(sgn*.50,.73,-.40,.24,.27),(sgn*.53,.58,-.34,.235,.26),(sgn*.53,.42,-.365,.18,.19),(sgn*.525,.29,-.47,.125,.145),(sgn*.52,.18,-.52,.13,.145),(sgn*.52,.12,-.49,.205,.235),(sgn*.52,.05,-.475,.21,.25),(sgn*.52,0,-.475,.205,.25)])
 # Match a real three-toed outline to the existing12vertex closed branch loop.
 toe=[(-1,-.5),(-1,.3),(-.8,1),(-.4,1),(-.29,.60),(-.2,1.12),(.2,1.12),(.29,.60),(.4,1),(.8,1),(1,.3),(1,-.5)]
 def fit_score(points):return sum(abs(math.atan2(math.sin(math.atan2(z,x)-t),math.cos(math.atan2(z,x)-t)))for (x,z),t in zip(points,angles))
 candidates=[]
 for points in [toe,list(reversed(toe))]:
  for shift in range(12):candidates.append(points[shift:]+points[:shift])
 toe=min(candidates,key=fit_score)
 prev=loop
 for k,(x,y,z,rx,rz)in enumerate(chain):
  ring=[]
  for jj,theta in enumerate(angles):
   xx=math.cos(theta);zz=math.sin(theta)
   if k>=6:xx,zz=toe[jj]
   ring.append(len(v));v.append((x+sgn*rx*xx,y,z+rz*zz))
  for j in range(len(loop)):
   f.append((prev[j],prev[(j+1)%len(loop)],ring[(j+1)%len(loop)],ring[j]));colors.append('cyan'if k>=6 else'blue')
  prev=ring
 f.append(tuple(reversed(prev)));colors.append('cyanShade');soles.append({'name':label,'center':[chain[-1][0],0,chain[-1][2]],'vertices':prev})
 landmarks[label+'Shoulder'if fore else label+'Hip']=[sgn*.40,.85 if fore else .80,.38 if fore else-.45]
 for name,item in zip(['Elbow'if fore else'Stifle','Wrist'if fore else'Hock','Paw'],[chain[3],chain[5],chain[-1]]):landmarks[label+name]=list(item[:3])
body=mesh('Connected torso skull tail and four paw chains',v,f,colors,'TidefinBody',refine=True)
# Single thick continuous three-peak crest with opaque buried root strip.
crest=[(-.73,1.025,1.04),(-.57,1.105,1.29),(-.38,1.145,1.17),(-.25,1.165,1.44),(-.06,1.19,1.22),(.07,1.21,1.55),(.27,1.235,1.28),(.36,1.26,1.27)]
cv=[];cf=[];cc=[]
for z,root,top in crest:cv.extend([(-.07,root-.04,z),(.07,root-.04,z),(-.024,top,z),(.024,top,z)])
for i in range(len(crest)-1):
 a=i*4;b=a+4
 for face,color in [((a,b,b+1,a+1),'cyanShade'),((a,a+2,b+2,b),'cyan'),((a+1,b+1,b+3,a+3),'cyanLight'),((a+2,a+3,b+3,b+2),'cyanLight')]:cf.append(face);cc.append(color)
cf.extend([(0,1,3,2),(28,30,31,29)]);cc.extend(['cyan','cyan']);mesh('Continuous three peak dorsal crest',cv,cf,cc)
# Shallow closed cheek wedges sampled against the actual connected body surface.
# Center-fan facets follow curvature; no nonplanar n-gon chord or deep box extrusion.
body_surface=BVHTree.FromPolygons([vv.co.copy()for vv in body.data.vertices],[list(poly.vertices)for poly in body.data.polygons])
def skull_surface(sgn,yy,zz):
 hit,normal,index,distance=body_surface.ray_cast(Vector((sgn*2,-zz,yy)),Vector((-sgn,0,0)))
 assert hit is not None,(yy,zz)
 return abs(hit.x)
for sgn in[-1,1]:
 # Broad front/middle plate; the shallow split occupies only the rear quarter.
 outline=[(.915,1.015),(.72,1.10),(.425,1.025),(.495,.925),(.455,.805),(.665,.735),(.855,.795),(.915,.925)]
 cy=.925;cz=.735;count=len(outline)
 nodes=[(cz,cy,.047)]+[(zz,yy,.025)for zz,yy in outline]
 faces2=[];mids={}
 def mid(a,b):
  key=tuple(sorted((a,b)))
  if key not in mids:
   aa=nodes[a];bb=nodes[b];mids[key]=len(nodes);nodes.append(tuple((aa[k]+bb[k])*.5 for k in range(3)))
  return mids[key]
 # One shallow subdivision of the small plate only, with actual-surface samples
 # at mids: removes the front cap chord that previously exposed a dark notch.
 for jj in range(count):
  aa=0;bb=jj+1;cc=(jj+1)%count+1;ab=mid(aa,bb);bc=mid(bb,cc);ca=mid(cc,aa)
  faces2.extend([(aa,ab,ca),(ab,bb,bc),(ca,bc,cc),(ab,bc,ca)])
 verts=[]
 for layer in[0,1]:
  for zz,yy,relief in nodes:
   verts.append((sgn*(skull_surface(sgn,yy,zz)+(relief if layer else-.012)),yy,zz))
 # Test triangle interiors, not just sampled corners, against the curved shoulder.
 # Correct only local outer vertices where a chord falls inside the body surface.
 nn=len(nodes);initial_outer=[abs(point[0])for point in verts[nn:]]
 for iteration in range(4):
  shifts=[0.0]*nn
  for tri2 in faces2:
   points=[verts[nn+k]for k in tri2]
   for aa in range(5):
    for bb in range(5-aa):
     weights=[aa/4,bb/4,1-(aa+bb)/4]
     yy=sum(w*p[1]for w,p in zip(weights,points));zz=sum(w*p[2]for w,p in zip(weights,points));xx=sum(w*abs(p[0])for w,p in zip(weights,points))
     deficit=skull_surface(sgn,yy,zz)+.009-xx
     if deficit>0:
      for k in tri2:shifts[k]=max(shifts[k],deficit)
  for k,shift in enumerate(shifts):
   xx,yy,zz=verts[nn+k];verts[nn+k]=(sgn*(abs(xx)+shift),yy,zz)
 extra=max(abs(verts[nn+k][0])-initial_outer[k]for k in range(nn));assert extra<.10,('cheek local clearance too thick',extra)
 print('CHEEK_LOCAL_CLEARANCE',sgn,extra)
 faces=[];cc=[];nn=len(nodes)
 for tri2 in faces2:
  faces.extend([tuple(reversed(tri2)),tuple(nn+k for k in tri2)]);cc.extend(['ivoryShade','ivory'])
 for jj in range(count):
  aa=jj+1;bb=(jj+1)%count+1;mm=mids[tuple(sorted((aa,bb)))];
  for aa,bb in[(aa,mm),(mm,bb)]:faces.append((aa,bb,nn+bb,nn+aa));cc.append('ivoryShade')
 mesh(('Left'if sgn>0 else'Right')+' broad shallow split cheek plate',verts,faces,cc)
 # Closed paired socket/eye discs; roots buried in skull along symmetrical forward/outward normals.
 normal=Vector((sgn*.73,.14,.67)).normalized();u=Vector((0,1,0));u=(u-normal*u.dot(normal)).normalized();w=normal.cross(u)
 base=Vector((sgn*.377,1.15,.942))
 def disc(name,center,rx,ry,depth,color):
  vv=[];ff=[]
  for h,r in[(-depth,.86),(0,1),(depth,.72)]:
   for j in range(16):
    q=j*2*math.pi/16;irregular=([1,.78,.90,1.25,1.05,.70,.92,1.20][j//2]if 'socket'in name else 1)
    vv.append(tuple(center+normal*h+u*math.cos(q)*ry*r*irregular+w*math.sin(q)*rx*r*irregular))
  ff.append(tuple(reversed(range(16))))
  for k in range(2):
   for j in range(16):ff.append((k*16+j,k*16+(j+1)%16,(k+1)*16+(j+1)%16,(k+1)*16+j))
  ff.append(tuple(range(32,48)));return mesh(name,vv,ff,[color])
 disc(('Left'if sgn>0 else'Right')+' ivory eye socket',base,.101,.080,.006,'ivory')
 disc(('Left'if sgn>0 else'Right')+' inset dark eye',base+normal*.010,.069,.067,.012,'eye')
 disc(('Left'if sgn>0 else'Right')+' eye glint',base+normal*.036+u*.023-w*.013,.011,.013,.002,'glint')
objects=[ob for group in groups.values()for ob in group]
# Exact grounded meter envelope; axes stay aligned and bilateral symmetry is retained.
def bounds(obs):
 pts=[ob.matrix_world@vert.co for ob in obs if ob.type=='MESH'for vert in ob.data.vertices];return[min(p[i]for p in pts)for i in range(3)],[max(p[i]for p in pts)for i in range(3)]
lo,hi=bounds(objects);scale=(1.48/(hi[0]-lo[0]),2.77/(hi[1]-lo[1]),1.55/(hi[2]-lo[2]))
for ob in objects:
 for vert in ob.data.vertices:vert.co.x*=scale[0];vert.co.y*=scale[1];vert.co.z*=scale[2]
for key,point in landmarks.items():landmarks[key]=[point[0]*scale[0],point[1]*scale[2],point[2]*scale[1]]
for foot in soles:foot.pop('vertices');foot['center']=[foot['center'][0]*scale[0],0,foot['center'][2]*scale[1]]
lo,hi=bounds(objects);tri=sum(len(poly.vertices)-2 for ob in objects for poly in ob.data.polygons);assert tri<12000,tri
anatomy={'forward':'+Z game/glTF','headSpineAligned':True,'bilateralPairAxis':'X','feetY':0,'landmarksGameMeters':landmarks,'soleCenters':soles,'limbConstruction':'Four actual torso boundary openings continued through explicit shoulder/haunch, lower leg and single broad paw loops; same closed mesh. Source rings linearly refined once without smoothing.','crest':'Single closed root strip with three peaks; roots overlap dorsal body by40mm before normalization.','head':'Same continuous axial surface as chest/pelvis/tail; no independent yaw. Paired socket/cheek details static and unrigged.','limitations':'Neutral geometry only. Joint landmarks provisional; no weights, bind matrices or animation acceptance.'}
(out/'anatomy.json').write_text(json.dumps(anatomy,indent=2),encoding='utf-8')
bpy.ops.wm.save_as_mainfile(filepath=str(out/'tidefin-editable.blend'))
for name,items in groups.items():
 bpy.ops.object.select_all(action='DESELECT')
 for ob in items:ob.select_set(True)
 bpy.context.view_layer.objects.active=items[0];bpy.ops.object.join();bpy.context.object.name=name
bpy.ops.wm.save_as_mainfile(filepath=str(out/'tidefin-batches.blend'))
bpy.ops.export_scene.gltf(filepath=str(out/'tidefin.glb'),export_format='GLB',export_yup=True,export_animations=False)
glb=out/'tidefin.glb';sha=hashlib.sha256(glb.read_bytes()).hexdigest()
manifest={'assetId':'asset_wildkin_tidefin','sourceMethod':'Procedural Blender authored closed loops; not image-to-3D','referenceSHA256':'d2931db2212729592cf54d90e40b7a16fd7dff4282c9ee6ed0b386aa04b559de','referenceReview':'Independent PREGEN PASS8.3','modelReview':'Pending independent neutral shape gate','sha256':sha,'fileBytes':glb.stat().st_size,'triangles':tri,'batches':2,'materials':1,'texture':[256,256],'dimensionsGameMeters':[hi[0]-lo[0],hi[2]-lo[2],hi[1]-lo[1]],'boundsBlender':{'min':lo,'max':hi},'scaleApplied':scale,'anatomy':'anatomy.json','runtimeEdits':False,'rigging':'none'}
(out/'manifest.json').write_text(json.dumps(manifest,indent=2),encoding='utf-8');print(json.dumps(manifest))
# Fresh export-only six-view evidence; exactGLB geometry/poses, no source duplicate.
bpy.ops.wm.read_factory_settings(use_empty=True);bpy.ops.import_scene.gltf(filepath=str(glb));model=list(bpy.context.scene.objects);lo,hi=bounds(model)
(out/'export-bounds.json').write_text(json.dumps({'sourceSHA256':sha,'boundsBlender':{'min':lo,'max':hi},'dimensionsGameMeters':[hi[0]-lo[0],hi[2]-lo[2],hi[1]-lo[1]],'baseY':lo[2]},indent=2),encoding='utf-8')
scene=bpy.context.scene;scene.render.engine='CYCLES';scene.cycles.device='CPU';scene.cycles.samples=20;scene.cycles.use_denoising=True;scene.render.threads_mode='FIXED';scene.render.threads=4;scene.render.resolution_x=512;scene.render.resolution_y=512;scene.render.resolution_percentage=100;scene.view_settings.view_transform='Standard'
world=bpy.data.worlds.new('Neutral studio');world.use_nodes=True;world.node_tree.nodes['Background'].inputs[0].default_value=(.65,.66,.67,1);world.node_tree.nodes['Background'].inputs[1].default_value=.75;scene.world=world
bpy.ops.mesh.primitive_plane_add(size=200,location=(0,0,-.012));floor=bpy.context.object;fm=bpy.data.materials.new('Floor');fm.diffuse_color=(.58,.59,.60,1);floor.data.materials.append(fm)
def look(ob,target):ob.rotation_euler=(Vector(target)-ob.location).to_track_quat('-Z','Y').to_euler()
for pos,power,size in[((-3,-4,6),700,5),((4,0,4),350,4)]:
 bpy.ops.object.light_add(type='AREA',location=pos);light=bpy.context.object;light.data.energy=power;light.data.size=size;look(light,(0,0,.7))
bpy.ops.object.camera_add();cam=bpy.context.object;scene.camera=cam;cam.data.type='ORTHO';cam.data.ortho_scale=3.65
views=[('front',(0,-7,2.2)),('front3q',(4,-6,2.65)),('side',(7,0,2.0)),('opposite',(-7,0,2.0)),('rear',(0,7,2.1)),('underside',(3,-5,-1.25))]
if options.primary_only:views=views[:3]
for name,pos in views:
 floor.hide_render=name=='underside';cam.location=pos;look(cam,(0,0,.72));scene.render.filepath=str(out/(name+'.png'));bpy.ops.render.render(write_still=True)
(out/'render-evidence.json').write_text(json.dumps({'sourceSHA256':sha,'engine':'Cycles CPU','threads':4,'samples':20,'resolution':[512,512],'views':[{'file':n+'.png','cameraBlender':p,'target':[0,0,.72],'orthoScale':3.65}for n,p in views]},indent=2),encoding='utf-8')
