// Read-only numerical feasibility for one Rootbound 2m terrain-facet proposal.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createFrontierChunk, sampleFrontier } from '../../../../src/world/frontierTerrain.js';
import { ROOTBOUND_CURATED_SCENERY } from '../../../../src/world/frontierRootbound.js';
const here=path.dirname(fileURLToPath(import.meta.url)), repo=path.resolve(here,'../../../../');
const out=path.join(here,'feasibility.json');
const plan={id:'rootbound-lantern-threshold-facet-r1',bounds:{minX:-460,maxX:-450,minZ:682,maxZ:690},center:{x:-456,z:686},amplitude:0.095,fadeM:2};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)); const smooth=t=>{t=clamp(t,0,1);return t*t*(3-2*t)};
function delta(x,z){const dx=(x-plan.center.x)/5,dz=(z-plan.center.z)/4;const fade=smooth(1-Math.max(Math.abs(dx),Math.abs(dz)));return plan.amplitude*fade*(1-.4*dx-.3*dz)}
function normal(a,b,c){const u=[b[0]-a[0],b[1]-a[1],b[2]-a[2]],v=[c[0]-a[0],c[1]-a[1],c[2]-a[2]];const n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]];const l=Math.hypot(...n);return n.map(x=>x/l)}
const chunk=createFrontierChunk(-9,13), grid=[];for(let z=682;z<=690;z+=2)for(let x=-460;x<=-450;x+=2){const base=sampleFrontier(x,z).height,d=delta(x,z);grid.push({x,z,baselineHeight:base,delta:d,candidateHeight:base+d})}
const by=new Map(grid.map(v=>[`${v.x},${v.z}`,v]));const faces=[];for(let z=682;z<690;z+=2)for(let x=-460;x<-450;x+=2){const A=by.get(`${x},${z}`),B=by.get(`${x+2},${z}`),C=by.get(`${x},${z+2}`),D=by.get(`${x+2},${z+2}`);for(const tri of [[A,C,B],[B,C,D]]){const as=tri.map(q=>[q.x,q.baselineHeight,q.z]),cs=tri.map(q=>[q.x,q.candidateHeight,q.z]);const n0=normal(...as),n1=normal(...cs);faces.push({vertices:tri.map(q=>[q.x,q.z]),baselineNormal:n0,candidateNormal:n1,normalAngleDeg:Math.acos(clamp(n0.reduce((s,v,i)=>s+v*n1[i],0),-1,1))*180/Math.PI})}}
const source=fs.readFileSync(path.join(repo,'src/world/frontierRootbound.js'),'utf8');const life=JSON.parse('['+source.match(/const PROTECTED_LIFE_POINTS = Object\.freeze\(\[([\s\S]*?)\]\);/)[1].replace(/,\s*$/,'')+']');const distance=(x,z,p)=>Math.hypot(x-p[0],z-p[1]);const nearest=(items)=>items.map(p=>({point:p,distanceM:Math.min(...grid.map(v=>distance(v.x,v.z,p)))})).sort((a,b)=>a.distanceM-b.distanceM)[0];const curated=ROOTBOUND_CURATED_SCENERY.map(p=>({key:p.key,x:p.x,z:p.z,distanceM:Math.min(...grid.map(v=>Math.hypot(v.x-p.x,v.z-p.z)))})).sort((a,b)=>a.distanceM-b.distanceM);
// Native destination capture: player [-449,9.5599,675], yaw -2.3, pitch 36°, FOV 52°.
const yaw=-2.3,pitch=Math.PI*.2,center=[-449,10.459936929465313,675],horizontal=6.55,height=5,f=[-Math.sin(yaw)*Math.cos(pitch),-Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)],camera=[center[0]-f[0]*horizontal,center[1]+height,center[2]-f[2]*horizontal],right=[Math.cos(yaw),0,-Math.sin(yaw)],up=[f[1]*right[2]-f[2]*right[1],f[2]*right[0]-f[0]*right[2],f[0]*right[1]-f[1]*right[0]];const project=(p)=>{const q=[p[0]-camera[0],p[1]-camera[1],p[2]-camera[2]],depth=q.reduce((s,v,i)=>s+v*f[i],0),aspect=412/915,tan=Math.tan(52*Math.PI/360);return {depthM:depth,xNdc:q.reduce((s,v,i)=>s+v*right[i],0)/(depth*tan*aspect),yNdc:q.reduce((s,v,i)=>s+v*up[i],0)/(depth*tan)}};const projected=grid.map(v=>({x:v.x,z:v.z,baseline:project([v.x,v.baselineHeight,v.z]),candidate:project([v.x,v.candidateHeight,v.z])}));
const result={schema:'rootbound-terrain-facets-r1-feasibility-v1',inputs:{terrainChunk:'-9,13',meshStepM:2,materialAlreadyFlatShaded:true,camera:{capture:'restart-r2 destination',player:[-449,9.559901237487793,675],center,camera,fovDeg:52}},proposal:plan,meshVertices:grid,triangles:faces,summary:{changedVertices:grid.filter(v=>Math.abs(v.delta)>1e-9).length,maxAbsDeltaM:Math.max(...grid.map(v=>Math.abs(v.delta))),normalAngleDeg:{min:Math.min(...faces.map(f=>f.normalAngleDeg)),max:Math.max(...faces.map(f=>f.normalAngleDeg)),mean:faces.reduce((s,f)=>s+f.normalAngleDeg,0)/faces.length},projectedVerticalNdcDelta:{max:Math.max(...projected.map(p=>Math.abs(p.candidate.yNdc-p.baseline.yNdc))),changedVertices:projected.filter(p=>Math.abs(p.candidate.yNdc-p.baseline.yNdc)>0).length}},protection:{nearestLifeVertex:nearest(life),curatedDistances:curated,plateCheck:'candidate lies z<700, outside three protected resident plates'},projection:projected,limits:['Read-only proposal: no current runtime sampler includes this delta.','Current Rootbound query and ordinary mesh both use sampleFrontierRaw at 2m; a source pass must add this same final local term in that shared chain.','Curated source positions/transforms and life points are unchanged; full footprint/hull checks remain implementation gates.']};fs.writeFileSync(out,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result.summary));
