#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const JSON_PATH = path.join(ROOT, "src", "world", "data", "world.json");
const GEN_PATH = path.join(ROOT, "src", "world", "data", "world.generated.js");
const WRAPPER_PATH = path.join(ROOT, "src", "world", "data", "world.js");

function sortedClone(value) {
  if (Array.isArray(value)) return value.map(sortedClone);
  if (value && typeof value === "object") {
    const out = {};
    const keys = Object.keys(value).sort();
    for (const k of keys) out[k] = sortedClone(value[k]);
    return out;
  }
  return value;
}

function stringifyStable(obj) {
  return JSON.stringify(sortedClone(obj), null, 2);
}

async function main() {
  // Step 5: support optional split sources — if src/world/data/sources/*.json exists, merge them deterministically
  const SOURCES_DIR = path.join(ROOT, "src", "world", "data", "sources");
  let raw;
  let parsed;
  if (fs.existsSync(SOURCES_DIR)) {
    const files = fs.readdirSync(SOURCES_DIR).filter(f => f.endsWith(".json")).sort();
    if (files.length > 0) {
      console.log(`[generate-world] merging ${files.length} source files from ${path.relative(ROOT, SOURCES_DIR)}`);
      // Base is world.json if it exists, else empty
      let base = {};
      if (fs.existsSync(JSON_PATH)) {
        try { base = JSON.parse(fs.readFileSync(JSON_PATH, "utf-8")); } catch {}
      }
      // Merge strategy: shallow merge for top-level keys, arrays concatenated with dedup by id where possible
      for (const file of files) {
        const content = JSON.parse(fs.readFileSync(path.join(SOURCES_DIR, file), "utf-8"));
        for (const [key, value] of Object.entries(content)) {
          if (Array.isArray(value) && Array.isArray(base[key])) {
            // dedup by id if items have id
            const seen = new Set(base[key].map(v => v?.id).filter(Boolean));
            for (const item of value) {
              if (item?.id && seen.has(item.id)) continue;
              base[key].push(item);
            }
          } else if (value && typeof value === "object" && base[key] && typeof base[key] === "object" && !Array.isArray(value)) {
            base[key] = { ...base[key], ...value };
          } else {
            base[key] = value;
          }
        }
      }
      parsed = base;
      raw = JSON.stringify(parsed);
    } else {
      raw = fs.readFileSync(JSON_PATH, "utf-8");
      try { parsed = JSON.parse(raw); } catch (e) { console.error("[generate-world] invalid JSON", e.message); process.exit(1); }
    }
  } else {
    raw = fs.readFileSync(JSON_PATH, "utf-8");
    try { parsed = JSON.parse(raw); } catch (e) { console.error("[generate-world] invalid JSON", e.message); process.exit(1); }
  }
  // Validate via normalize if available
  try {
    const { normalizeWorldData } = await import(pathToFileURL(path.join(ROOT, "src", "world", "worldValidator.js")).href);
    normalizeWorldData(parsed);
  } catch (e) {
    console.error("[generate-world] validation failed:", e.message);
    process.exit(1);
  }
  const stable = sortedClone(parsed);
  const jsonStable = JSON.stringify(stable, null, 2) + "\n";
  // Re-write JSON in stable deterministic form (so export is byte-stable)
  // Only write if different to avoid churn? But determinism requires stable file anyway.
  const prettyJson = jsonStable;
  // If JSON file not stable, we could overwrite, but we want to keep it stable — write back if needed for determinism
  const currentJson = raw;
  // Normalize for comparison: parse and re-stringify sorted
  const currentStable = JSON.stringify(sortedClone(JSON.parse(currentJson)), null, 2) + "\n";
  if (currentStable !== prettyJson) {
    // Keep original file as is? But for deterministic export we should ensure stable order next time
    // For now, don't auto-overwrite JSON unless --fix
  }

  const jsContent = `// GENERATED FILE — do not edit manually. Source: world.json
// This file is generated by tools/generate-world.mjs from src/world/data/world.json
// Run: npm run world:generate

export const WORLD_DATA = ${JSON.stringify(stable, null, 2)};

export default WORLD_DATA;
`;

  // Ensure deterministic: sortedClone already sorts, but JSON.stringify preserves insertion order from sortedClone
  // Write generated file
  fs.writeFileSync(GEN_PATH, jsContent, "utf-8");
  console.log(`[generate-world] wrote ${path.relative(ROOT, GEN_PATH)}`);

  // Ensure wrapper exists (thin re-export, not a mirror)
  const wrapperContent = `// src/world/data/world.js — thin wrapper around generated data
// DO NOT maintain world data here. Single source is world.json -> world.generated.js
export { WORLD_DATA } from "./world.generated.js";
export { default } from "./world.generated.js";
export { WORLD_DATA as defaultData } from "./world.generated.js";
`;
  if (!fs.existsSync(WRAPPER_PATH) || fs.readFileSync(WRAPPER_PATH, "utf-8") !== wrapperContent) {
    fs.writeFileSync(WRAPPER_PATH, wrapperContent, "utf-8");
    console.log(`[generate-world] wrote wrapper ${path.relative(ROOT, WRAPPER_PATH)}`);
  }

  // Verify wrapper and generated are in sync by doing a quick check
  console.log("[generate-world] done — validate with: npm run world:check");
}

function pathToFileURL(p) {
  // Node's file URL for dynamic import
  let resolved = path.resolve(p);
  // Windows needs forward slashes
  resolved = resolved.replace(/\\/g, "/");
  if (!resolved.startsWith("/")) resolved = "/" + resolved;
  return new URL("file://" + resolved);
}

main().catch(e=>{ console.error(e); process.exit(1); });
